/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uabc.algoritmos.yugioh.upgrade;

import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author JesusOmar Leal
 */
public class CollectionIDE extends javax.swing.JFrame {

    Audio audio = new Audio();
    LectorCSV lector = new LectorCSV();
    boolean ordenarAscendente = true;
    ImageIcon imagen;
    Icon icono;

    /**
     * Creates new form CollectionIDE
     */
    public CollectionIDE() {

        initComponents();
        lector.obtenerLista();
        audio.playAudio();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        EscogerNiveles = new javax.swing.JComboBox<>();
        EscogerAtributos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MostrarTodasCartas = new javax.swing.JButton();
        MostrarPorNivel = new javax.swing.JButton();
        MostrarPorAtributo = new javax.swing.JButton();
        MostrarPorAtaque = new javax.swing.JButton();
        MostrarPorDefensa = new javax.swing.JButton();
        OrganizarAltoBajoValor = new javax.swing.JCheckBox();
        OrganizarBajoAltoValor = new javax.swing.JCheckBox();
        logo = new javax.swing.JLabel();
        mute = new javax.swing.JToggleButton();
        ChooseLevelB = new javax.swing.JButton();
        ChooseAtributeB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EscogerNiveles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        EscogerNiveles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscogerNivelesActionPerformed(evt);
            }
        });

        EscogerAtributos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DARK", "EARTH", "FIRE", "LIGHT", "SPELL", "TRAP", "WATER", "WIND" }));
        EscogerAtributos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscogerAtributosActionPerformed(evt);
            }
        });

        jLabel3.setText("Choose Level");

        jLabel4.setText("Choose Attribute");

        MostrarTodasCartas.setText("Show All Cards");
        MostrarTodasCartas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarTodasCartasActionPerformed(evt);
            }
        });

        MostrarPorNivel.setText("Show By Level");
        MostrarPorNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarPorNivelActionPerformed(evt);
            }
        });

        MostrarPorAtributo.setText("Show By Attribute");
        MostrarPorAtributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarPorAtributoActionPerformed(evt);
            }
        });

        MostrarPorAtaque.setText("Show By Attack Points");
        MostrarPorAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarPorAtaqueActionPerformed(evt);
            }
        });

        MostrarPorDefensa.setText("Show By Defense Points");
        MostrarPorDefensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarPorDefensaActionPerformed(evt);
            }
        });

        buttonGroup1.add(OrganizarAltoBajoValor);
        OrganizarAltoBajoValor.setText("High To Low (Z-A)");
        OrganizarAltoBajoValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrganizarAltoBajoValorActionPerformed(evt);
            }
        });

        buttonGroup1.add(OrganizarBajoAltoValor);
        OrganizarBajoAltoValor.setSelected(true);
        OrganizarBajoAltoValor.setText("Low To High (A-Z)");
        OrganizarBajoAltoValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrganizarBajoAltoValorActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\YugiOH-upgrade\\src\\main\\java\\com\\uabc\\algoritmos\\yugioh\\upgrade\\assets\\logo.png")); // NOI18N

        mute.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\YugiOH-upgrade\\src\\main\\java\\com\\uabc\\algoritmos\\yugioh\\upgrade\\assets\\off.png")); // NOI18N
        mute.setBorderPainted(false);
        mute.setContentAreaFilled(false);
        mute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                muteMouseReleased(evt);
            }
        });
        mute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muteActionPerformed(evt);
            }
        });

        ChooseLevelB.setText("...");
        ChooseLevelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseLevelBActionPerformed(evt);
            }
        });

        ChooseAtributeB.setText("...");
        ChooseAtributeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseAtributeBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(logo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(MostrarTodasCartas, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(MostrarPorNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(EscogerNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChooseLevelB))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(MostrarPorAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(MostrarPorAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(EscogerAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(ChooseAtributeB))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(mute)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(MostrarPorDefensa)
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrganizarAltoBajoValor)
                    .addComponent(OrganizarBajoAltoValor))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {MostrarPorAtaque, MostrarPorAtributo, MostrarPorDefensa, MostrarPorNivel, MostrarTodasCartas});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {EscogerAtributos, EscogerNiveles});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(logo)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MostrarTodasCartas)
                    .addComponent(jLabel3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MostrarPorNivel))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EscogerNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ChooseLevelB)))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MostrarPorAtributo)
                    .addComponent(jLabel4))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MostrarPorAtaque))
                    .addComponent(EscogerAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChooseAtributeB))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MostrarPorDefensa)
                    .addComponent(OrganizarAltoBajoValor))
                .addGap(12, 12, 12)
                .addComponent(OrganizarBajoAltoValor)
                .addGap(18, 18, 18)
                .addComponent(mute))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {MostrarPorAtaque, MostrarPorAtributo, MostrarPorDefensa, MostrarPorNivel, MostrarTodasCartas});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {EscogerAtributos, EscogerNiveles});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChooseAtributeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseAtributeBActionPerformed

        String Atributo = EscogerAtributos.getSelectedItem().toString();
        ListaCircularDoble<String[]> nuevasCartas = new ListaCircularDoble<>();
        NodoDoble<String[]> inicio = lector.getCartas().getInicio();
        NodoDoble<String[]> current = lector.getCartas().getInicio();

        while (current.getSig() != inicio) {
            String nivelCartaStr = current.getInfo()[7];
            if (!nivelCartaStr.isEmpty()) {
                String atributoCarta = current.getInfo()[7];

                if (atributoCarta.equals(Atributo)) {
                    nuevasCartas.insertaFin(current.getInfo());
                }
            }
            current = current.getSig();
        }

        lector.setCartas(nuevasCartas);
        VentanaOrdenamientos ordenamientos = new VentanaOrdenamientos();
        ordenamientos.setVisible(true);
        ordenamientos.setLocationRelativeTo(null);

        lector.clear();
        lector.obtenerLista();
    }//GEN-LAST:event_ChooseAtributeBActionPerformed

    private void ChooseLevelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseLevelBActionPerformed

        int nivel = Integer.parseInt(EscogerNiveles.getSelectedItem().toString());

        ListaCircularDoble<String[]> nuevasCartas = new ListaCircularDoble<>();
        NodoDoble<String[]> inicio = lector.getCartas().getInicio();
        NodoDoble<String[]> current = lector.getCartas().getInicio();

        while (current.getSig() != inicio) {
            String nivelCartaStr = current.getInfo()[6];
            if (!nivelCartaStr.isEmpty()) {
                int nivelCarta = Integer.parseInt(nivelCartaStr);

                if (nivelCarta == nivel) {

                    nuevasCartas.insertaFin(current.getInfo());
                }
            }
            current = current.getSig();
        }

        lector.setCartas(nuevasCartas);

        VentanaOrdenamientos ordenamientos = new VentanaOrdenamientos();
        ordenamientos.setVisible(true);
        ordenamientos.setLocationRelativeTo(null);

        lector.clear();
        lector.obtenerLista();
    }//GEN-LAST:event_ChooseLevelBActionPerformed

    private void muteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muteActionPerformed
        if (audio.isAudioPlaying()) {
            audio.stopAudio();
        } else {
            audio.playAudio();
        }
    }//GEN-LAST:event_muteActionPerformed

    private void muteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_muteMouseReleased

    }//GEN-LAST:event_muteMouseReleased

    private void OrganizarBajoAltoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrganizarBajoAltoValorActionPerformed
        this.ordenarAscendente = true;
    }//GEN-LAST:event_OrganizarBajoAltoValorActionPerformed

    private void OrganizarAltoBajoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrganizarAltoBajoValorActionPerformed
        this.ordenarAscendente = false;
    }//GEN-LAST:event_OrganizarAltoBajoValorActionPerformed

    private void MostrarPorDefensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarPorDefensaActionPerformed

        lector.clear();
        lector.obtenerLista();
        ordenarPorDefensa();

        VentanaOrdenamientos ordenamientos = new VentanaOrdenamientos();
        ordenamientos.setVisible(true);
        ordenamientos.setLocationRelativeTo(null);

    }//GEN-LAST:event_MostrarPorDefensaActionPerformed

    private void MostrarPorAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarPorAtaqueActionPerformed

        lector.clear();
        lector.obtenerLista();
        ordenarPorAtaque();

        VentanaOrdenamientos ordenamientos = new VentanaOrdenamientos();
        ordenamientos.setVisible(true);
        ordenamientos.setLocationRelativeTo(null);

    }//GEN-LAST:event_MostrarPorAtaqueActionPerformed

    private void MostrarPorAtributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarPorAtributoActionPerformed

        lector.clear();
        lector.obtenerLista();
        ordenarPorAtributo();

        VentanaOrdenamientos ordenamientos = new VentanaOrdenamientos();
        ordenamientos.setVisible(true);
        ordenamientos.setLocationRelativeTo(null);

    }//GEN-LAST:event_MostrarPorAtributoActionPerformed

    private void MostrarPorNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarPorNivelActionPerformed

        lector.clear();
        lector.obtenerLista();
        ordenarPorNivel();

        VentanaOrdenamientos ordenamientos = new VentanaOrdenamientos();
        ordenamientos.setVisible(true);
        ordenamientos.setLocationRelativeTo(null);

    }//GEN-LAST:event_MostrarPorNivelActionPerformed

    private void MostrarTodasCartasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarTodasCartasActionPerformed
        lector.clear();
        lector.obtenerLista();

        VentanaOrdenamientos ordenamientos = new VentanaOrdenamientos();
        ordenamientos.setVisible(true);
        ordenamientos.setLocationRelativeTo(null);
    }//GEN-LAST:event_MostrarTodasCartasActionPerformed

    private void EscogerAtributosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscogerAtributosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscogerAtributosActionPerformed

    private void EscogerNivelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscogerNivelesActionPerformed

    }//GEN-LAST:event_EscogerNivelesActionPerformed
    public void ordenarPorNivel() {
        NodoDoble<String[]> current = lector.getCartas().getInicio();
        NodoDoble<String[]> inicio = lector.getCartas().getInicio();

        do {
            NodoDoble<String[]> siguiente = current.getSig();

            while (siguiente != inicio) {
                String[] filaActual = current.getInfo();
                String[] filaSiguiente = siguiente.getInfo();

                String nivelActualStr = filaActual[6];
                String nivelSiguienteStr = filaSiguiente[6];

                if (!nivelActualStr.isEmpty() && !nivelSiguienteStr.isEmpty()) {

                    int nivelActual = Integer.parseInt(nivelActualStr);
                    int nivelSiguiente = Integer.parseInt(nivelSiguienteStr);

                    boolean intercambiar = (ordenarAscendente && nivelActual > nivelSiguiente)
                            || (!ordenarAscendente && nivelActual < nivelSiguiente);

                    if (intercambiar) {
                        String[] temp = filaActual;
                        current.setInfo(filaSiguiente);
                        siguiente.setInfo(temp);
                    }
                } else {
                    if (nivelActualStr.isEmpty()) {
                        lector.eliminarCarta(current);
                    } else {
                        lector.eliminarCarta(siguiente);
                    }
                }

                siguiente = siguiente.getSig();
            }

            current = current.getSig();
        } while (current != inicio);
    }

    public void ordenarPorAtributo() {

        NodoDoble<String[]> current = lector.getCartas().getInicio();
        NodoDoble<String[]> inicio = lector.getCartas().getInicio();

        do {
            NodoDoble<String[]> siguiente = current.getSig();

            while (siguiente != inicio) {
                String[] filaActual = current.getInfo();
                String[] filaSiguiente = siguiente.getInfo();

                String nivelActualStr = filaActual[7];
                String nivelSiguienteStr = filaSiguiente[7];

                if (!nivelActualStr.isEmpty() && !nivelSiguienteStr.isEmpty()) {

                    int comparacion = nivelActualStr.compareTo(nivelSiguienteStr);

                    boolean intercambiar = (ordenarAscendente && comparacion > 0)
                            || (!ordenarAscendente && comparacion < 0);

                    if (intercambiar) {
                        String[] temp = filaActual;
                        current.setInfo(filaSiguiente);
                        siguiente.setInfo(temp);
                    }
                } else {
                    if (nivelActualStr.isEmpty()) {
                        lector.eliminarCarta(current);
                    } else {
                        lector.eliminarCarta(siguiente);
                    }
                }

                siguiente = siguiente.getSig();
            }

            current = current.getSig();
        } while (current != inicio);

    }


    public void ordenarPorAtaque() {
        NodoDoble<String[]> current = lector.getCartas().getInicio();
        NodoDoble<String[]> inicio = lector.getCartas().getInicio();

        do {
            NodoDoble<String[]> siguiente = current.getSig();

            while (siguiente != inicio) {
                String[] filaActual = current.getInfo();
                String[] filaSiguiente = siguiente.getInfo();

                String nivelActualStr = filaActual[4];
                String nivelSiguienteStr = filaSiguiente[4];

                if (!nivelActualStr.isEmpty() && !nivelSiguienteStr.isEmpty()) {

                    int nivelActual = Integer.parseInt(nivelActualStr);
                    int nivelSiguiente = Integer.parseInt(nivelSiguienteStr);

                    boolean intercambiar = (ordenarAscendente && nivelActual > nivelSiguiente)
                            || (!ordenarAscendente && nivelActual < nivelSiguiente);

                    if (intercambiar) {
                        String[] temp = filaActual;
                        current.setInfo(filaSiguiente);
                        siguiente.setInfo(temp);
                    }
                } else {
                    if (nivelActualStr.isEmpty()) {
                        lector.eliminarCarta(current);
                    } else {
                        lector.eliminarCarta(siguiente);
                    }
                }

                siguiente = siguiente.getSig();
            }

            current = current.getSig();
        } while (current != inicio);
    }

    public void ordenarPorDefensa() {
        NodoDoble<String[]> current = lector.getCartas().getInicio();
        NodoDoble<String[]> inicio = lector.getCartas().getInicio();

        do {
            NodoDoble<String[]> siguiente = current.getSig();

            while (siguiente != inicio) {
                String[] filaActual = current.getInfo();
                String[] filaSiguiente = siguiente.getInfo();

                String nivelActualStr = filaActual[5];
                String nivelSiguienteStr = filaSiguiente[5];

                if (!nivelActualStr.isEmpty() && !nivelSiguienteStr.isEmpty()) {

                    int nivelActual = Integer.parseInt(nivelActualStr);
                    int nivelSiguiente = Integer.parseInt(nivelSiguienteStr);

                    boolean intercambiar = (ordenarAscendente && nivelActual > nivelSiguiente)
                            || (!ordenarAscendente && nivelActual < nivelSiguiente);

                    if (intercambiar) {
                        String[] temp = filaActual;
                        current.setInfo(filaSiguiente);
                        siguiente.setInfo(temp);
                    }
                } else {
                    if (nivelActualStr.isEmpty()) {
                        lector.eliminarCarta(current);
                    } else {
                        lector.eliminarCarta(siguiente);
                    }
                }

                siguiente = siguiente.getSig();
            }

            current = current.getSig();
        } while (current != inicio);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CollectionIDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CollectionIDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CollectionIDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CollectionIDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CollectionIDE().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChooseAtributeB;
    private javax.swing.JButton ChooseLevelB;
    private javax.swing.JComboBox<String> EscogerAtributos;
    private javax.swing.JComboBox<String> EscogerNiveles;
    private javax.swing.JButton MostrarPorAtaque;
    private javax.swing.JButton MostrarPorAtributo;
    private javax.swing.JButton MostrarPorDefensa;
    private javax.swing.JButton MostrarPorNivel;
    private javax.swing.JButton MostrarTodasCartas;
    private javax.swing.JCheckBox OrganizarAltoBajoValor;
    private javax.swing.JCheckBox OrganizarBajoAltoValor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logo;
    private javax.swing.JToggleButton mute;
    // End of variables declaration//GEN-END:variables
}
